-- --------------------------------------------------------
-- Host:                         192.168.33.10
-- Versión del servidor:         5.6.33 - MySQL Community Server (GPL)
-- SO del servidor:              Linux
-- HeidiSQL Versión:             9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Volcando estructura de base de datos para xualidb
DROP DATABASE IF EXISTS `xualidb`;
CREATE DATABASE IF NOT EXISTS `xualidb` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `xualidb`;


-- Volcando estructura para tabla xualidb.ACTIVIDAD
DROP TABLE IF EXISTS `ACTIVIDAD`;
CREATE TABLE IF NOT EXISTS `ACTIVIDAD` (
  `CD_ACTIVIDAD` varchar(20) NOT NULL DEFAULT '',
  `NM_ACTIVIDAD` varchar(150) NOT NULL,
  `DS_ACTIVIDAD` varchar(300) DEFAULT NULL,
  `AM_PUNTOS` int(11) DEFAULT NULL,
  PRIMARY KEY (`CD_ACTIVIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.COMPONENTE
DROP TABLE IF EXISTS `COMPONENTE`;
CREATE TABLE IF NOT EXISTS `COMPONENTE` (
  `ID_COMPONENTE` int(11) NOT NULL DEFAULT '0',
  `DS_COMPONENTE` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID_COMPONENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.EMPLEADO
DROP TABLE IF EXISTS `EMPLEADO`;
CREATE TABLE IF NOT EXISTS `EMPLEADO` (
  `ID_EMPLEADO` int(11) NOT NULL,
  `ID_ENTIDAD` int(11) NOT NULL,
  `CD_TIPO_DOCUMENTO` varchar(20) NOT NULL,
  `ID_DOCUMENTO` varchar(20) NOT NULL,
  `NOMBRE1` varchar(100) NOT NULL,
  `NOMBRE2` varchar(100) DEFAULT NULL,
  `APELLIDO1` varchar(100) NOT NULL,
  `APELLIDO2` varchar(100) DEFAULT NULL,
  `CD_ROL` varchar(20) NOT NULL,
  `CD_ESTADO` char(1) DEFAULT NULL,
  `DT_ADDED` datetime NOT NULL,
  `ID_ADDED` int(11) NOT NULL,
  PRIMARY KEY (`ID_EMPLEADO`),
  KEY `EMPLEADO_ENTIDAD` (`ID_ENTIDAD`),
  KEY `EMPLEADO_ROL` (`CD_ROL`),
  CONSTRAINT `EMPLEADO_ENTIDAD` FOREIGN KEY (`ID_ENTIDAD`) REFERENCES `ENTIDAD` (`ID_ENTIDAD`),
  CONSTRAINT `EMPLEADO_ROL` FOREIGN KEY (`CD_ROL`) REFERENCES `ROL` (`CD_ROL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.ENTIDAD
DROP TABLE IF EXISTS `ENTIDAD`;
CREATE TABLE IF NOT EXISTS `ENTIDAD` (
  `ID_ENTIDAD` int(11) NOT NULL,
  `NM_ENTIDAD` varchar(150) NOT NULL,
  `DS_ENTIDAD` varchar(250) DEFAULT NULL,
  `DIRECCION` varchar(250) DEFAULT NULL,
  `URL_LOGO` varchar(250) DEFAULT NULL,
  `URL_PORTADA` varchar(250) DEFAULT NULL,
  `URL_WEBSITE` varchar(250) DEFAULT NULL,
  `CD_ESTADO` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID_ENTIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Entidades';

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.HISTORIA
DROP TABLE IF EXISTS `HISTORIA`;
CREATE TABLE IF NOT EXISTS `HISTORIA` (
  `ID_HISTORIA` int(11) NOT NULL DEFAULT '0',
  `ID_TEMA` int(11) DEFAULT NULL,
  `CD_TYPE` varchar(20) DEFAULT NULL,
  `TITLE_HISTORIA` varchar(150) DEFAULT NULL,
  `DS_INTRO` varchar(250) DEFAULT NULL,
  `DS_HISTORIA` text,
  `URL_PORTADA` varchar(250) DEFAULT NULL,
  `URL_HISTORIA` varchar(250) DEFAULT NULL,
  `PUNTO_DECISION` int(11) DEFAULT NULL,
  `CD_ESTADO` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID_HISTORIA`),
  KEY `HISTORIA_TEMA` (`ID_TEMA`),
  CONSTRAINT `HISTORIA_TEMA` FOREIGN KEY (`ID_TEMA`) REFERENCES `TEMA` (`ID_TEMA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.NIVEL
DROP TABLE IF EXISTS `NIVEL`;
CREATE TABLE IF NOT EXISTS `NIVEL` (
  `CD_NIVEL` varchar(20) NOT NULL DEFAULT '',
  `NM_NIVEL` varchar(20) DEFAULT NULL,
  `DS_NIVEL` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`CD_NIVEL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.NIVEL_COMPETENCIA
DROP TABLE IF EXISTS `NIVEL_COMPETENCIA`;
CREATE TABLE IF NOT EXISTS `NIVEL_COMPETENCIA` (
  `CD_NIVEL` varchar(20) NOT NULL DEFAULT '',
  `ID_COMPETENCIA` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`CD_NIVEL`,`ID_COMPETENCIA`),
  KEY `NIVEL_COMP_COMPETENCIA` (`ID_COMPETENCIA`),
  CONSTRAINT `NIVEL_COMP_COMPETENCIA` FOREIGN KEY (`ID_COMPETENCIA`) REFERENCES `TEMA` (`ID_TEMA`),
  CONSTRAINT `NIVEL_COMP_NIVEL` FOREIGN KEY (`CD_NIVEL`) REFERENCES `NIVEL` (`CD_NIVEL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.PREGUNTA
DROP TABLE IF EXISTS `PREGUNTA`;
CREATE TABLE IF NOT EXISTS `PREGUNTA` (
  `ID_PREGUNTA` int(11) NOT NULL DEFAULT '0',
  `ID_USUARIO` int(11) DEFAULT NULL,
  `DS_TITULO` varchar(150) DEFAULT NULL,
  `DS_PREGUNTA` varchar(300) DEFAULT NULL,
  `DT_PREGUNTA` datetime DEFAULT NULL,
  `CD_ESTADO` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID_PREGUNTA`),
  KEY `PREGUNTA_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `PREGUNTA_USUARIO` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.PUNTO_DECISION
DROP TABLE IF EXISTS `PUNTO_DECISION`;
CREATE TABLE IF NOT EXISTS `PUNTO_DECISION` (
  `ID_PUNTO_DECISION` int(11) NOT NULL DEFAULT '0',
  `DS_DECISION` varchar(250) DEFAULT NULL,
  `ID_HISTORIA_1` int(11) DEFAULT NULL,
  `ID_HISTORIA_2` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_PUNTO_DECISION`),
  KEY `DECISION_HISTORIA1` (`ID_HISTORIA_1`),
  KEY `DECISION_HISTORIA2` (`ID_HISTORIA_2`),
  CONSTRAINT `DECISION_HISTORIA1` FOREIGN KEY (`ID_HISTORIA_1`) REFERENCES `HISTORIA` (`ID_HISTORIA`),
  CONSTRAINT `DECISION_HISTORIA2` FOREIGN KEY (`ID_HISTORIA_2`) REFERENCES `HISTORIA` (`ID_HISTORIA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.RESPUESTA
DROP TABLE IF EXISTS `RESPUESTA`;
CREATE TABLE IF NOT EXISTS `RESPUESTA` (
  `ID_RESPUESTA` int(11) NOT NULL DEFAULT '0',
  `ID_PREGUNTA` int(11) DEFAULT NULL,
  `ID_EMPLEADO` int(11) DEFAULT NULL,
  `DS_RESPUESTA` varchar(500) DEFAULT NULL,
  `DT_RESPUESTA` datetime DEFAULT NULL,
  `CD_STADO` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID_RESPUESTA`),
  KEY `RESPUESTA_EMPLEADO` (`ID_EMPLEADO`),
  KEY `RESPUESTA_PREGUNTA` (`ID_PREGUNTA`),
  CONSTRAINT `RESPUESTA_EMPLEADO` FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `EMPLEADO` (`ID_EMPLEADO`),
  CONSTRAINT `RESPUESTA_PREGUNTA` FOREIGN KEY (`ID_PREGUNTA`) REFERENCES `PREGUNTA` (`ID_PREGUNTA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.ROL
DROP TABLE IF EXISTS `ROL`;
CREATE TABLE IF NOT EXISTS `ROL` (
  `CD_ROL` varchar(20) NOT NULL,
  `NM_ROL` varchar(100) NOT NULL,
  PRIMARY KEY (`CD_ROL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.TEMA
DROP TABLE IF EXISTS `TEMA`;
CREATE TABLE IF NOT EXISTS `TEMA` (
  `ID_TEMA` int(11) NOT NULL DEFAULT '0',
  `ID_COMPONENTE` int(11) DEFAULT NULL,
  `DS_COMPETENCIA` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID_TEMA`),
  KEY `COMPETENCIA_COMPONENTE` (`ID_COMPONENTE`),
  CONSTRAINT `COMPETENCIA_COMPONENTE` FOREIGN KEY (`ID_COMPONENTE`) REFERENCES `COMPONENTE` (`ID_COMPONENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.TIPO_DOCUMENTO
DROP TABLE IF EXISTS `TIPO_DOCUMENTO`;
CREATE TABLE IF NOT EXISTS `TIPO_DOCUMENTO` (
  `CD_TIPO_DOCUMENTO` varchar(20) DEFAULT NULL,
  `NM_TIPO_DOCUMENTO` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.USUARIO
DROP TABLE IF EXISTS `USUARIO`;
CREATE TABLE IF NOT EXISTS `USUARIO` (
  `ID_USUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `CD_TIPO_DOCUMENTO` varchar(20) NOT NULL,
  `ID_DOCUMENTO` varchar(20) NOT NULL,
  `NOMBRE` varchar(100) NOT NULL,
  `DS_EMAIL` varchar(150) NOT NULL,
  `DS_PASSWORD` varchar(150) NOT NULL,
  `DT_NACIMIENTO` date DEFAULT NULL,
  `URL_FACEBOOK` varchar(300) DEFAULT NULL,
  `URL_TWITTER` varchar(300) DEFAULT NULL,
  `CD_ESTADO` varchar(20) DEFAULT 'A',
  PRIMARY KEY (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.USUARIO_ACTIVIDAD
DROP TABLE IF EXISTS `USUARIO_ACTIVIDAD`;
CREATE TABLE IF NOT EXISTS `USUARIO_ACTIVIDAD` (
  `ID_USUARIO` int(11) NOT NULL DEFAULT '0',
  `CD_ACTIVIDAD` varchar(20) NOT NULL DEFAULT '',
  `DT_ACTIVIDAD` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `AM_PUNTOS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`,`CD_ACTIVIDAD`,`DT_ACTIVIDAD`),
  KEY `USUARIO_ACT_ACTIVIDAD` (`CD_ACTIVIDAD`),
  CONSTRAINT `USUARIO_ACT_ACTIVIDAD` FOREIGN KEY (`CD_ACTIVIDAD`) REFERENCES `ACTIVIDAD` (`CD_ACTIVIDAD`),
  CONSTRAINT `USUARIO_ACT_USUARIO` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.


-- Volcando estructura para tabla xualidb.USUARIO_ENTIDAD
DROP TABLE IF EXISTS `USUARIO_ENTIDAD`;
CREATE TABLE IF NOT EXISTS `USUARIO_ENTIDAD` (
  `ID_ENTIDAD` int(11) NOT NULL DEFAULT '0',
  `CD_TIPO_DOCUMENTO` varchar(20) NOT NULL DEFAULT '',
  `ID_DOCUMENTO` int(11) NOT NULL DEFAULT '0',
  `NOMBRE1` varchar(100) DEFAULT NULL,
  `NOMBRE2` varchar(100) DEFAULT NULL,
  `APELLIDO1` varchar(100) DEFAULT NULL,
  `APELLIDO2` varchar(100) DEFAULT NULL,
  `DT_NACIMIENTO` date DEFAULT NULL,
  `DT_ADDED` date DEFAULT NULL,
  `ID_EMPLEADO` int(11) DEFAULT NULL,
  `ID_USUARIO` int(11) DEFAULT NULL,
  `CD_ESTADO` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID_ENTIDAD`,`CD_TIPO_DOCUMENTO`,`ID_DOCUMENTO`),
  KEY `USU_ENTIDAD_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `USU_ENTIDAD_ENTIDAD` FOREIGN KEY (`ID_ENTIDAD`) REFERENCES `ENTIDAD` (`ID_ENTIDAD`),
  CONSTRAINT `USU_ENTIDAD_USUARIO` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
